version: "3"

services:
  ghost:
    image: ghost
    container_name: asd
    volumes: 
      - ./docker-mount:/var/lib/ghost/content/themes/theme-name:rw,z
    ports: 
      - "asd:2368"
    environment:
      - url=http://localhost:asd

